// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: center.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CenterNodeBridgeService_PushNodeStatus_FullMethodName = "/tmpro.CenterNodeBridgeService/PushNodeStatus"
)

// CenterNodeBridgeServiceClient is the client API for CenterNodeBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CenterNodeBridgeServiceClient interface {
	PushNodeStatus(ctx context.Context, in *ServerStatusQuery, opts ...grpc.CallOption) (*ServerStatusResponse, error)
}

type centerNodeBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCenterNodeBridgeServiceClient(cc grpc.ClientConnInterface) CenterNodeBridgeServiceClient {
	return &centerNodeBridgeServiceClient{cc}
}

func (c *centerNodeBridgeServiceClient) PushNodeStatus(ctx context.Context, in *ServerStatusQuery, opts ...grpc.CallOption) (*ServerStatusResponse, error) {
	out := new(ServerStatusResponse)
	err := c.cc.Invoke(ctx, CenterNodeBridgeService_PushNodeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CenterNodeBridgeServiceServer is the server API for CenterNodeBridgeService service.
// All implementations must embed UnimplementedCenterNodeBridgeServiceServer
// for forward compatibility
type CenterNodeBridgeServiceServer interface {
	PushNodeStatus(context.Context, *ServerStatusQuery) (*ServerStatusResponse, error)
	mustEmbedUnimplementedCenterNodeBridgeServiceServer()
}

// UnimplementedCenterNodeBridgeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCenterNodeBridgeServiceServer struct {
}

func (UnimplementedCenterNodeBridgeServiceServer) PushNodeStatus(context.Context, *ServerStatusQuery) (*ServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushNodeStatus not implemented")
}
func (UnimplementedCenterNodeBridgeServiceServer) mustEmbedUnimplementedCenterNodeBridgeServiceServer() {
}

// UnsafeCenterNodeBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CenterNodeBridgeServiceServer will
// result in compilation errors.
type UnsafeCenterNodeBridgeServiceServer interface {
	mustEmbedUnimplementedCenterNodeBridgeServiceServer()
}

func RegisterCenterNodeBridgeServiceServer(s grpc.ServiceRegistrar, srv CenterNodeBridgeServiceServer) {
	s.RegisterService(&CenterNodeBridgeService_ServiceDesc, srv)
}

func _CenterNodeBridgeService_PushNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerStatusQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CenterNodeBridgeServiceServer).PushNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CenterNodeBridgeService_PushNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CenterNodeBridgeServiceServer).PushNodeStatus(ctx, req.(*ServerStatusQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// CenterNodeBridgeService_ServiceDesc is the grpc.ServiceDesc for CenterNodeBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CenterNodeBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tmpro.CenterNodeBridgeService",
	HandlerType: (*CenterNodeBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushNodeStatus",
			Handler:    _CenterNodeBridgeService_PushNodeStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "center.proto",
}
